### ISSUE TITLE
px-chart-* redraws on each scroll in iOS and mobile browsers.

### ISSUE THREAD

**Issue by jonniespratley** [predixdesignsystem/px-simple-chart-common-behavior#1]
## Expected behavior and actual behavior:
- Device should scroll without refreshing the charts.
## Steps to reproduce the problem:
- Open any application using charts in simulator or on device, and scroll the page.

**Comment by randyaskin** [comment]
I don't see this issue with any of the simple charts on iOS Safari or Chrome. Maybe this refers to the old deprecated HighCharts px-chart, which I think also used this common-behavior?
